---
sidebar: sidebar
permalink: reference-new.html
keywords: new, new features, features, release notes, enhancements
summary: Cloud Volumes ONTAP 9.12.0 includes a new enhancement.
---

= What's new in Cloud Volumes ONTAP 9.12.0
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Cloud Volumes ONTAP 9.12.0 includes a new enhancement.

Additional features and enhancements are also introduced in the latest versions of BlueXP. See the https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html[BlueXP Release Notes^] for details.

== 9.12.0 P1 (15 Dec 2022)

Cloud Volumes ONTAP 9.12.0 P1 is now available in AWS and Google Cloud. This release includes the following new feature.

=== Support for m6id.32xlarge in AWS

Cloud Volumes ONTAP is now supported with the m6id.32xlarge EC2 instance type in AWS.

Go to the link:reference-configs-aws.html[supported configurations page] for more details.

== Upgrade notes

Read through these notes to learn more about upgrading to this release.

=== How to upgrade

Upgrades of Cloud Volumes ONTAP must be completed from BlueXP. You should not upgrade Cloud Volumes ONTAP by using System Manager or the CLI. Doing so can impact system stability.

http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html[Learn how to upgrade when BlueXP notifies you^].

=== Supported upgrade path

You can upgrade to Cloud Volumes ONTAP 9.12.0 from the 9.11.1 release. BlueXP will prompt you to upgrade eligible Cloud Volumes ONTAP systems to this release.

=== Required version of the Connector

The BlueXP Connector must be running version 3.9.24 or later to deploy new Cloud Volumes ONTAP 9.12.0 systems and to upgrade existing systems to this release.

TIP: Automatic upgrades of the Connector are enabled by default so you should be running the latest version.

=== Downtime

* The upgrade of a single node system takes the system offline for up to 25 minutes, during which I/O is interrupted.

* Upgrading an HA pair is nondisruptive and I/O is uninterrupted. During this nondisruptive upgrade process, each node is upgraded in tandem to continue serving I/O to clients.
